### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by buczi11** [di4b0lical/No-ADS-YouTube#10]
Hi, 
how to uninstall the script?

Thanks

**Comment by di4b0lical** [comment]
😭 

Just remove the script from Tampermonkey.

if you are having issues with the script and thats the reason for uninstallation, make sure you are on the latest version.

**Comment by buczi11** [comment]
On the contrary, the script works perfectly 😊 I am unearthly surprised. I just fired it up and don't know where to look for it in case of a problem 🤭

**Comment by di4b0lical** [comment]
To find the script, open up Tampermonkey extension and then look for the No Ads YouTube script. You can then make fixes or adjustments to your liking. If you have any recommendations or any fixes/improvements, feel free to push them my way 🙏🏻
