### ISSUE TITLE
AD Blocks not longer work

### ISSUE THREAD

**Issue by CasparTrost** [di4b0lical/No-ADS-YouTube#13]
Hi,

The script seems to be no longer working. ADS are not skipped anymore. Did youtube change something on their side?

**Comment by di4b0lical** [comment]
I just tested it and it's skipping and muting ads. Please make sure you are on the latest version and that you have it correctly installed as well as enabled along with tampermonkey.

**Comment by SamGun-Official** [comment]
It works on most ads but recently there are types of unskippable ads which no longer skippable and the text itself says "Video plays soon" or something like that.

**Comment by kopach** [comment]
Same here. And since code is minified now it's much harder do debug. Any chance to revert that? IMO, minification is not needed for such script

**Comment by di4b0lical** [comment]
> Same here. And since code is minified now it's much harder do debug. Any chance to revert that? IMO, minification is not needed for such script

just put it through a code beautifier

**Comment by di4b0lical** [comment]
> It works on most ads but recently there are types of unskippable ads which no longer skippable and the text itself says "Video plays soon" or something like that.

Please show me an example if possible

**Comment by SamGun-Official** [comment]
> > It works on most ads but recently there are types of unskippable ads which no longer skippable and the text itself says "Video plays soon" or something like that.
> 
> Please show me an example if possible

Hi, thanks for responding. Here's some example of the "unskippable" ads:
![Screenshot_6](https://github.com/di4b0lical/No-ADS-YouTube/assets/93367073/e88f824a-f56a-4c78-b494-bb6d2d9caeb7)

It says "Video plays soon" and this type of ads is still showing even with script enabled. Typically when ads is 5 seconds long, the button would show something like "The video will play after ads", and when it's more than 5 seconds, ads can be skipped by clicking button "Skip ads". These type of ads are skippable through your script, but not with the ads that I've mentioned. It's more than 5 seconds long, it's unskippable (cannot pressed skip button and script did nothing), and I have to wait until it's done. These type of ads is appearing at random time. Sometimes at the start of video, sometimes in the middle of the video, and sometimes not appearing at all.

Just a suggestion, maybe you should re-check #14 again when you encounter this type of ads. @kopach did change something at the if statement. I don't know how to quote his code so I'll just screenshot the difference.

Here's your code:
![image](https://github.com/di4b0lical/No-ADS-YouTube/assets/93367073/c5c0590c-2952-4069-b874-a8a0598c9aa8)

And here's the changes @kopach made:
![image](https://github.com/di4b0lical/No-ADS-YouTube/assets/93367073/750b6730-f5c8-4551-8be0-80d08793aea3)

**Comment by sandy0096** [comment]
replace `ytp-ad-preview-text` with `ytp-ad-preview-text-modern`

**Comment by di4b0lical** [comment]
fixed, v2.1
